development:
  password: shptka_6439c9aafb7080403f3d7ac1c8bf369b
  theme_id: "120839077965" # CCC 1.0.0 Rebuild [wip 3/17/22 aa]
  # theme_id: "120839012429" # github/main
  # theme_id: # Don't forget to update your Theme ID :)
  store: counter-culture-coffee-retail.myshopify.com
